### ISSUE TITLE
VS 2022 unsupported for installation

### ISSUE THREAD

**Issue by Branskugel** [emartineau/SelectionWrapper#11]
Please, update it for Visual Studio 2022, I severely miss this extension in the newest version
I'd be eternally grateful

**Comment by lfr** [comment]
In the meantime I've modified the existing one so that it can be installed with Visual Studio 2022, it did require me to restart VS twice for some reason, once when prompted and once just to get the wrapping to happen in the editor:
[SelectionWrapper.vsix.2022_rename.zip](https://github.com/emartineau/SelectionWrapper/files/7624998/SelectionWrapper.vsix.2022_rename.zip) (rename to SelectionWrapper.vsix)

In case it helps it's installed to this folder on my machine:
`C:\Users\<WINUSER>\AppData\Local\Microsoft\VisualStudio\17.0_831aa387\Extensions\rd0jb20z.yie`

**Comment by Branskugel** [comment]
Thank you so much! It was a real pain to wrap code manually without your extension. Now I'm 10 000% happier and my issue is resolved!

**Comment by lfr** [comment]
Sure thing, if @emartineau doesn't resurface before the end of the year I think I'll fork the repo to make sure this extension survives.

**Comment by ronykalfarisi** [comment]
> In the meantime I've modified the existing one so that it can be installed with Visual Studio 2022, it did require me to restart VS twice for some reason, once when prompted and once just to get the wrapping to happen in the editor: [SelectionWrapper.vsix.2022_rename.zip](https://github.com/emartineau/SelectionWrapper/files/7624998/SelectionWrapper.vsix.2022_rename.zip) (rename to SelectionWrapper.vsix)
> 
> In case it helps it's installed to this folder on my machine: `C:\Users\<WINUSER>\AppData\Local\Microsoft\VisualStudio\17.0_831aa387\Extensions\rd0jb20z.yie`

Hi @lfr , can you tell me step by step how to install this manually? Thanks

**Comment by lfr** [comment]
Hello @ronykalfarisi, from memory you just download and rename the file to "SelectionWrapper.vsix" and then double click on it.

**Comment by ronykalfarisi** [comment]
I see, I thought I need to unzip the file first. Silly me, thank you so much @lfr
